### ISSUE TITLE
Support for php 5.4

### ISSUE THREAD

**Issue by maxiloc** [vinkla/algolia#1]
Hey,

I am currently working on an Algolia extension for laravel that integrate with Eloquent ORM. I would like to use you package (which is great by the way) as a dependency. We would like to support php 5.4 because laravel 5.0 and laravel 5.1 still support php 5.4.

Can you consider putting back the support for it ?

Cheers,

**Comment by vinkla** [comment]
We just recently dropped it in [`1.1.0`](https://github.com/vinkla/algolia/releases/tag/1.1.0). PHP `5.4` will be discontinued in september this year, wont be supported anymore. If Laravel adapts the latest Symfony `3.0` modules in the next version, it will mean PHP `>=5.5.9` is the least required PHP version. That is the reason behind the decision.

**Comment by vinkla** [comment]
@maxiloc Let me know if you guys need any help creating the package. I would be happy to help out!

**Comment by maxiloc** [comment]
@vinkla Php 5.4 is probably going to stay in production with laravel 5.0 for a while so we are gonna need to support it. I think It is not a big deal to support it since the codebase is still compatible. What do you think? We can still fork your repository to add its support but it would be simpler not to.

**Comment by vinkla** [comment]
Then maybe a fork is the way to go until the next release of Laravel with Symfony `3.0`. Let me know if you need any help setting it up!
