### ISSUE TITLE
Does it only support the algolia client 1.0?

### ISSUE THREAD

**Issue by rogeryu23** [vinkla/algolia#2]
Hi Vincent, seems it is still using the 1.0 php client of algolia, will that be upgraded to latest version?

thanks
Roger

**Comment by maxiloc** [comment]
:+1: @vinkla  Yes will be a good thing to update it as it implement new retry strategy and fixes bug

**Comment by vinkla** [comment]
Is `2.0` out already? Must have missed that. Sorry if I've.

**Comment by maxiloc** [comment]
Yes we are at 1.5.*

Le jeudi 11 juin 2015, Vincent Klaiber <notifications@github.com> a écrit :

> Is 2.0 out already? Must have missed that. Sorry if I've.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vinkla/algolia/issues/2#issuecomment-111222125>.
>


-- 
Maxime Locqueville

**Comment by vinkla** [comment]
Ahh okay, then its no problem. `~1.0` means everything below `2.0`.
