### ISSUE TITLE
Errors shown when install

### ISSUE THREAD

**Issue by atom2ueki** [vinkla/algolia#4]
vinkla/algolia 2.2.0 requires graham-campbell/manager ^2.3 -> satisfiable by graham-campbell/manager[v2.3.0].
    - Conclusion: remove laravel/framework v5.0.34
    - Conclusion: don't install laravel/framework v5.0.34

Do I need to upgrade my laravel ?

**Comment by vinkla** [comment]
What version of Laravel are you using?

**Comment by atom2ueki** [comment]
@vinkla v5.0.34, but after upgraded to v5.1.x, this problem gone

**Comment by vinkla** [comment]
Okay, let's consider this solved then!
