### ISSUE TITLE
Outdated PHP API client version.

### ISSUE THREAD

**Issue by rayrutjes** [vinkla/algolia#5]
Hi @vinkla ,
We implemented a new fallback strategy in our PHP API Client since version 1.9.0, that allows the client to use different hosts when the default ones are busy (like today sadly...)

A lot of people are using your extension, and we really appreciate all the hard work by the way! 

Any chance you upgrade to the new client, so that the users benefit from the latest optimizations?

Cheers!

**Comment by rayrutjes** [comment]
Sorry, wrong one, everything looks good!

**Comment by vinkla** [comment]
Out of curiosity; what library are you talking about?

**Comment by maxiloc** [comment]
It was this one algolia/algoliasearch-client-php

**Comment by vinkla** [comment]
Is there a new version out?

**Comment by maxiloc** [comment]
Yes we release a new version every once in a while to have usually small fixes but some like last one (1.9.0) brings improvement to the retry strategy

**Comment by vinkla** [comment]
Okay cool. We should be fine though. We allow any 1.0 version.

**Comment by rayrutjes** [comment]
Yes you are repository is fine, the poor reading of the composer file is on me...

**Comment by vinkla** [comment]
No worries 😉
